### ISSUE TITLE
TCP SYN COUNT

### ISSUE THREAD

**Issue by boverhof** [esnet/tstat-transport#12]
We need the SYN packet count for a TCP flow (c_syn_cnt), which is present in the raw logs.

For example:

`boverhof@%head /home/data/tstat/2017_09_25_14_03.out/log_tcp_complete 
#09#c_ip:1 c_port:2 c_pkts_all:3 c_rst_cnt:4 c_ack_cnt:5 c_ack_cnt_p:6 c_bytes_uniq:7 c_pkts_data:8 c_bytes_all:9 c_pkts_retx:10 c_bytes_retx:11 c_pkts_ooo:12 c_syn_cnt:13 c_fin_cnt:14 s_ip:15 s_port:16 s_pkts_all:17 s_rst_cnt:18 s_ack_cnt:19 s_ack_cnt_p:20 s_bytes_uniq:21 s_pkts_data:22 s_bytes_all:23 s_pkts_retx:24 s_bytes_retx:25 s_pkts_ooo:26 s_syn_cnt:27 s_fin_cnt:28 first:29 last:30 durat:31 c_first:32 s_first:33 c_last:34 s_last:35 c_first_ack:36 s_first_ack:37 c_isint:38 s_isint:39 c_iscrypto:40 s_iscrypto:41 con_t:42 p2p_t:43 http_t:44 c_rtt_avg:45 c_rtt_min:46 c_rtt_max:47 c_rtt_std:48 c_rtt_cnt:49 c_ttl_min:50 c_ttl_max:51 s_rtt_avg:52 s_rtt_min:53 s_rtt_max:54 s_rtt_std:55 s_rtt_cnt:56 s_ttl_min:57 s_ttl_max:58 c_f1323_opt:59 c_tm_opt:60 c_win_scl:61 c_sack_opt:62 c_sack_cnt:63 c_mss:64 c_mss_max:65 c_mss_min:66 c_win_max:67 c_win_min:68 c_win_0:69 c_cwin_max:70 c_cwin_min:71 c_cwin_ini:72 c_pkts_rto:73 c_pkts_fs:74 c_pkts_reor:75 c_pkts_dup:76 c_pkts_unk:77 c_pkts_fc:78 c_pkts_unrto:79 c_pkts_unfs:80 c_syn_retx:81 s_f1323_opt:82 s_tm_opt:83 s_win_scl:84 s_sack_opt:85 s_sack_cnt:86 s_mss:87 s_mss_max:88 s_mss_min:89 s_win_max:90 s_win_min:91 s_win_0:92 s_cwin_max:93 s_cwin_min:94 s_cwin_ini:95 s_pkts_rto:96 s_pkts_fs:97 s_pkts_reor:98 s_pkts_dup:99 s_pkts_unk:100 s_pkts_fc:101 s_pkts_unrto:102 s_pkts_unfs:103 s_syn_retx:104`

Which results in 
`{
        “type”: “flow”,
        “interval”: 600,
        “values”: {
            “duration”: 173.49,
            “num_bits”: 6636932736,
            “num_packets”: 108995,
            “bits_per_second”: 38256306.65,
            “packets_per_second”: 628.26,
            “tcp_rexmit_bytes”: 414131,
            “tcp_rexmit_pkts”: 287,
            “tcp_rtt_avg”: 153.477,
            “tcp_rtt_min”: 153.064,
            “tcp_rtt_max”: 194.794,
            “tcp_rtt_std”: 0.797,
            “tcp_pkts_rto”: 0,
            “tcp_pkts_fs”: 2,
            “tcp_pkts_reor”: 0,
            “tcp_pkts_dup”: 0,
            “tcp_pkts_unk”: 284,
            “tcp_pkts_fc”: 0,
            “tcp_pkts_unrto”: 1,
            “tcp_pkts_unfs”: 0,
            “tcp_cwin_min”: 38,
            “tcp_cwin_max”: 5734080,
            “tcp_out_seq_pkts”: 0,
            “tcp_window_scale”: 11,
            “tcp_mss”: 1460,
            “tcp_max_seg_size”: 46336,
            “tcp_min_seg_size”: 38,
            “tcp_win_max”: 5734080,
            “tcp_win_min”: 38,
            “tcp_initial_cwin”: 279,
            “tcp_sack_cnt”: 13252
        },`

I think this will effect the change we need:
```
tstat-transport % git diff
diff --git a/tstat_transport/format.py b/tstat_transport/format.py
index c12cbe5..f0e21b0 100644
--- a/tstat_transport/format.py
+++ b/tstat_transport/format.py
@@ -244,6 +244,7 @@ class TcpCapsule(EntryCapsuleBase):
 
         val_doc = collections.OrderedDict(
             [
+                ('tcp_syn_cnt', self._directional_key('syn_cnt')),
                 ('tcp_rexmit_bytes', self._directional_key('bytes_retx')),
                 ('tcp_rexmit_pkts', self._directional_key('pkts_retx')),
                 ('tcp_rtt_avg', self._directional_key('rtt_avg')),
tstat-transport % 
```
thanks,
-josh

**Comment by safaci2000** [comment]
This is super dated, but I'll pull this into the next commit.

**Comment by safaci2000** [comment]
Fixed.
