### ISSUE TITLE
Investigate null IPs

### ISSUE THREAD

**Issue by montegoode** [esnet/tstat-transport#3]
we're seeing some messages like (last octet redacted):

"meta": {
   "src_ip": "193.146.75.x",
   "src_port": 1094,
   "dst_ip": null,
   "dst_port": 2533,
   "protocol": "tcp"
},

Any idea why some of the IPs are coming through as null?

**Comment by montegoode** [comment]
I see the problem, but I'll need some input from y'all that understand tstat better than me.

Consider this snippet of a header line from one of the tcp logs:

`#15#c_ip:1 c_port:2 c_pkts_all:3 c_rst_cnt:4 c_ack_cnt:5 c_ack_cnt_p:6 c_bytes_uniq:7`

See that garbage at the very beginning of the line?  I need to get rid of that when I am assembling the internal data structures.

When I did the original pass on this that garbage was `#09#` on all of the tcp logs, so I was trimming that off. Now it is different, so it's not being handled correctly, and that's what's causing those missing ip values.

So I need a new way to sanitize that key - at that point I have a dict with those individual values as keys.

```
#15#c_ip:1
c_port:2
c_pkts_all:3
```

etc.

I need a new rule, such as:
- that junk will always be prepended to the c_ip:1 header value.
- if there are # characters in a header key, only look at the characters to the right of the right-most # character
- etc.

The UDP logs have a similar condition: `#c_ip:1` - it looks like it's just a single # character. 

It would be great if this will always impact the `c_ip:1` key because I'll be able to use that substring to trigger the cleanse.

**Comment by bltierney** [comment]
I think its safe to just ignore everything before "c_ip:"

**Comment by apertome** [comment]
Interesting, I wonder if there is a reason for those extra characters. I just found in the tstat docs: 

http://tstat.polito.it/measure.shtml#log_tcp_complete

> Note for advanced users: the current log composition is encoded as a 'magic number' in the first characters of the header line, that starts with "#nn#", 'nn' being a bitmask indicating which set were active at the time of the logging. Interested users should refer to tstat.h for the bitmask values.

So it sounds like it's expected that that value may be different in different scenarios.

I don't see a similar note about UDP, but if you look at the bitmask there are some settings for UDP; maybe it's just not getting set correctly, or something:
http://tstat.polito.it/viewvc/software/tstat/trunk/tstat/tstat.h?view=markup#l820

As far as I know, you've worked directly with TSTAT data more than any of us, but I'll share this around and see if anyone here has some insight. My guess is that Brian is correct and we can just ignore anything preceding # and the '#' character itself.

**Comment by montegoode** [comment]
Resolved by examining the keys (not just `c_ip`) for the presence of a # character. If found, remove everything to the left of the right-most # character. Remove old hard coded values.
