### ISSUE TITLE
feature request: ability to send to more than 1 destination

### ISSUE THREAD

**Issue by bltierney** [esnet/tstat-transport#4]
I need the ability to send to more than 1 rabbit server. 

No big rush on this, but by the end of September would be nice.

**Comment by bltierney** [comment]
It was pointed out to me that this functionality is built into RabbitMQ, so this should not be needed. 
Let me see if I can get that to work.

**Comment by montegoode** [comment]
Oh, that's pretty cool. Pre-existing features are a happy thing.
